/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaguesRouteRouteImport } from './routes/_leagues/route'
import { Route as LeaguesIndexRouteImport } from './routes/_leagues/index'
import { Route as LeaguesLeagueSlugMatchesIndexRouteImport } from './routes/_leagues/$leagueSlug/matches/index'
import { Route as LeaguesLeagueSlugMatchesMatchIdRouteRouteImport } from './routes/_leagues/$leagueSlug/matches/$matchId/route'
import { Route as LeaguesLeagueSlugMatchesMatchIdIndexRouteImport } from './routes/_leagues/$leagueSlug/matches/$matchId/index'
import { Route as LeaguesLeagueSlugMatchesMatchIdStatsRouteImport } from './routes/_leagues/$leagueSlug/matches/$matchId/stats'
import { Route as LeaguesLeagueSlugMatchesMatchIdLineupsRouteImport } from './routes/_leagues/$leagueSlug/matches/$matchId/lineups'
import { Route as LeaguesLeagueSlugMatchesMatchIdH2hRouteImport } from './routes/_leagues/$leagueSlug/matches/$matchId/h2h'

const LeaguesRouteRoute = LeaguesRouteRouteImport.update({
  id: '/_leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIndexRoute = LeaguesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeaguesRouteRoute,
} as any)
const LeaguesLeagueSlugMatchesIndexRoute =
  LeaguesLeagueSlugMatchesIndexRouteImport.update({
    id: '/$leagueSlug/matches/',
    path: '/$leagueSlug/matches/',
    getParentRoute: () => LeaguesRouteRoute,
  } as any)
const LeaguesLeagueSlugMatchesMatchIdRouteRoute =
  LeaguesLeagueSlugMatchesMatchIdRouteRouteImport.update({
    id: '/$leagueSlug/matches/$matchId',
    path: '/$leagueSlug/matches/$matchId',
    getParentRoute: () => LeaguesRouteRoute,
  } as any)
const LeaguesLeagueSlugMatchesMatchIdIndexRoute =
  LeaguesLeagueSlugMatchesMatchIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LeaguesLeagueSlugMatchesMatchIdRouteRoute,
  } as any)
const LeaguesLeagueSlugMatchesMatchIdStatsRoute =
  LeaguesLeagueSlugMatchesMatchIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => LeaguesLeagueSlugMatchesMatchIdRouteRoute,
  } as any)
const LeaguesLeagueSlugMatchesMatchIdLineupsRoute =
  LeaguesLeagueSlugMatchesMatchIdLineupsRouteImport.update({
    id: '/lineups',
    path: '/lineups',
    getParentRoute: () => LeaguesLeagueSlugMatchesMatchIdRouteRoute,
  } as any)
const LeaguesLeagueSlugMatchesMatchIdH2hRoute =
  LeaguesLeagueSlugMatchesMatchIdH2hRouteImport.update({
    id: '/h2h',
    path: '/h2h',
    getParentRoute: () => LeaguesLeagueSlugMatchesMatchIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LeaguesIndexRoute
  '/$leagueSlug/matches/$matchId': typeof LeaguesLeagueSlugMatchesMatchIdRouteRouteWithChildren
  '/$leagueSlug/matches/': typeof LeaguesLeagueSlugMatchesIndexRoute
  '/$leagueSlug/matches/$matchId/h2h': typeof LeaguesLeagueSlugMatchesMatchIdH2hRoute
  '/$leagueSlug/matches/$matchId/lineups': typeof LeaguesLeagueSlugMatchesMatchIdLineupsRoute
  '/$leagueSlug/matches/$matchId/stats': typeof LeaguesLeagueSlugMatchesMatchIdStatsRoute
  '/$leagueSlug/matches/$matchId/': typeof LeaguesLeagueSlugMatchesMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LeaguesIndexRoute
  '/$leagueSlug/matches': typeof LeaguesLeagueSlugMatchesIndexRoute
  '/$leagueSlug/matches/$matchId/h2h': typeof LeaguesLeagueSlugMatchesMatchIdH2hRoute
  '/$leagueSlug/matches/$matchId/lineups': typeof LeaguesLeagueSlugMatchesMatchIdLineupsRoute
  '/$leagueSlug/matches/$matchId/stats': typeof LeaguesLeagueSlugMatchesMatchIdStatsRoute
  '/$leagueSlug/matches/$matchId': typeof LeaguesLeagueSlugMatchesMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_leagues': typeof LeaguesRouteRouteWithChildren
  '/_leagues/': typeof LeaguesIndexRoute
  '/_leagues/$leagueSlug/matches/$matchId': typeof LeaguesLeagueSlugMatchesMatchIdRouteRouteWithChildren
  '/_leagues/$leagueSlug/matches/': typeof LeaguesLeagueSlugMatchesIndexRoute
  '/_leagues/$leagueSlug/matches/$matchId/h2h': typeof LeaguesLeagueSlugMatchesMatchIdH2hRoute
  '/_leagues/$leagueSlug/matches/$matchId/lineups': typeof LeaguesLeagueSlugMatchesMatchIdLineupsRoute
  '/_leagues/$leagueSlug/matches/$matchId/stats': typeof LeaguesLeagueSlugMatchesMatchIdStatsRoute
  '/_leagues/$leagueSlug/matches/$matchId/': typeof LeaguesLeagueSlugMatchesMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$leagueSlug/matches/$matchId'
    | '/$leagueSlug/matches/'
    | '/$leagueSlug/matches/$matchId/h2h'
    | '/$leagueSlug/matches/$matchId/lineups'
    | '/$leagueSlug/matches/$matchId/stats'
    | '/$leagueSlug/matches/$matchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$leagueSlug/matches'
    | '/$leagueSlug/matches/$matchId/h2h'
    | '/$leagueSlug/matches/$matchId/lineups'
    | '/$leagueSlug/matches/$matchId/stats'
    | '/$leagueSlug/matches/$matchId'
  id:
    | '__root__'
    | '/_leagues'
    | '/_leagues/'
    | '/_leagues/$leagueSlug/matches/$matchId'
    | '/_leagues/$leagueSlug/matches/'
    | '/_leagues/$leagueSlug/matches/$matchId/h2h'
    | '/_leagues/$leagueSlug/matches/$matchId/lineups'
    | '/_leagues/$leagueSlug/matches/$matchId/stats'
    | '/_leagues/$leagueSlug/matches/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LeaguesRouteRoute: typeof LeaguesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_leagues': {
      id: '/_leagues'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LeaguesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_leagues/': {
      id: '/_leagues/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LeaguesIndexRouteImport
      parentRoute: typeof LeaguesRouteRoute
    }
    '/_leagues/$leagueSlug/matches/': {
      id: '/_leagues/$leagueSlug/matches/'
      path: '/$leagueSlug/matches'
      fullPath: '/$leagueSlug/matches/'
      preLoaderRoute: typeof LeaguesLeagueSlugMatchesIndexRouteImport
      parentRoute: typeof LeaguesRouteRoute
    }
    '/_leagues/$leagueSlug/matches/$matchId': {
      id: '/_leagues/$leagueSlug/matches/$matchId'
      path: '/$leagueSlug/matches/$matchId'
      fullPath: '/$leagueSlug/matches/$matchId'
      preLoaderRoute: typeof LeaguesLeagueSlugMatchesMatchIdRouteRouteImport
      parentRoute: typeof LeaguesRouteRoute
    }
    '/_leagues/$leagueSlug/matches/$matchId/': {
      id: '/_leagues/$leagueSlug/matches/$matchId/'
      path: '/'
      fullPath: '/$leagueSlug/matches/$matchId/'
      preLoaderRoute: typeof LeaguesLeagueSlugMatchesMatchIdIndexRouteImport
      parentRoute: typeof LeaguesLeagueSlugMatchesMatchIdRouteRoute
    }
    '/_leagues/$leagueSlug/matches/$matchId/stats': {
      id: '/_leagues/$leagueSlug/matches/$matchId/stats'
      path: '/stats'
      fullPath: '/$leagueSlug/matches/$matchId/stats'
      preLoaderRoute: typeof LeaguesLeagueSlugMatchesMatchIdStatsRouteImport
      parentRoute: typeof LeaguesLeagueSlugMatchesMatchIdRouteRoute
    }
    '/_leagues/$leagueSlug/matches/$matchId/lineups': {
      id: '/_leagues/$leagueSlug/matches/$matchId/lineups'
      path: '/lineups'
      fullPath: '/$leagueSlug/matches/$matchId/lineups'
      preLoaderRoute: typeof LeaguesLeagueSlugMatchesMatchIdLineupsRouteImport
      parentRoute: typeof LeaguesLeagueSlugMatchesMatchIdRouteRoute
    }
    '/_leagues/$leagueSlug/matches/$matchId/h2h': {
      id: '/_leagues/$leagueSlug/matches/$matchId/h2h'
      path: '/h2h'
      fullPath: '/$leagueSlug/matches/$matchId/h2h'
      preLoaderRoute: typeof LeaguesLeagueSlugMatchesMatchIdH2hRouteImport
      parentRoute: typeof LeaguesLeagueSlugMatchesMatchIdRouteRoute
    }
  }
}

interface LeaguesLeagueSlugMatchesMatchIdRouteRouteChildren {
  LeaguesLeagueSlugMatchesMatchIdH2hRoute: typeof LeaguesLeagueSlugMatchesMatchIdH2hRoute
  LeaguesLeagueSlugMatchesMatchIdLineupsRoute: typeof LeaguesLeagueSlugMatchesMatchIdLineupsRoute
  LeaguesLeagueSlugMatchesMatchIdStatsRoute: typeof LeaguesLeagueSlugMatchesMatchIdStatsRoute
  LeaguesLeagueSlugMatchesMatchIdIndexRoute: typeof LeaguesLeagueSlugMatchesMatchIdIndexRoute
}

const LeaguesLeagueSlugMatchesMatchIdRouteRouteChildren: LeaguesLeagueSlugMatchesMatchIdRouteRouteChildren =
  {
    LeaguesLeagueSlugMatchesMatchIdH2hRoute:
      LeaguesLeagueSlugMatchesMatchIdH2hRoute,
    LeaguesLeagueSlugMatchesMatchIdLineupsRoute:
      LeaguesLeagueSlugMatchesMatchIdLineupsRoute,
    LeaguesLeagueSlugMatchesMatchIdStatsRoute:
      LeaguesLeagueSlugMatchesMatchIdStatsRoute,
    LeaguesLeagueSlugMatchesMatchIdIndexRoute:
      LeaguesLeagueSlugMatchesMatchIdIndexRoute,
  }

const LeaguesLeagueSlugMatchesMatchIdRouteRouteWithChildren =
  LeaguesLeagueSlugMatchesMatchIdRouteRoute._addFileChildren(
    LeaguesLeagueSlugMatchesMatchIdRouteRouteChildren,
  )

interface LeaguesRouteRouteChildren {
  LeaguesIndexRoute: typeof LeaguesIndexRoute
  LeaguesLeagueSlugMatchesMatchIdRouteRoute: typeof LeaguesLeagueSlugMatchesMatchIdRouteRouteWithChildren
  LeaguesLeagueSlugMatchesIndexRoute: typeof LeaguesLeagueSlugMatchesIndexRoute
}

const LeaguesRouteRouteChildren: LeaguesRouteRouteChildren = {
  LeaguesIndexRoute: LeaguesIndexRoute,
  LeaguesLeagueSlugMatchesMatchIdRouteRoute:
    LeaguesLeagueSlugMatchesMatchIdRouteRouteWithChildren,
  LeaguesLeagueSlugMatchesIndexRoute: LeaguesLeagueSlugMatchesIndexRoute,
}

const LeaguesRouteRouteWithChildren = LeaguesRouteRoute._addFileChildren(
  LeaguesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LeaguesRouteRoute: LeaguesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
