/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as StandingsIndexRouteImport } from './routes/standings/index'
import { Route as TeamsTeamIdRouteRouteImport } from './routes/teams/$teamId/route'
import { Route as MatchesMatchIdRouteRouteImport } from './routes/_matches/$matchId/route'
import { Route as TeamsTeamIdIndexRouteImport } from './routes/teams/$teamId/index'
import { Route as MatchesMatchIdIndexRouteImport } from './routes/_matches/$matchId/index'
import { Route as TeamsTeamIdStatsRouteImport } from './routes/teams/$teamId/stats'
import { Route as TeamsTeamIdSquadRouteImport } from './routes/teams/$teamId/squad'
import { Route as TeamsTeamIdMatchesRouteImport } from './routes/teams/$teamId/matches'
import { Route as MatchesMatchIdStatsRouteImport } from './routes/_matches/$matchId/stats'
import { Route as MatchesMatchIdLineupsRouteImport } from './routes/_matches/$matchId/lineups'
import { Route as MatchesMatchIdH2hRouteImport } from './routes/_matches/$matchId/h2h'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsIndexRoute = StandingsIndexRouteImport.update({
  id: '/standings/',
  path: '/standings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRouteRoute = TeamsTeamIdRouteRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRouteRoute = MatchesMatchIdRouteRouteImport.update({
  id: '/_matches/$matchId',
  path: '/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdIndexRoute = TeamsTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const MatchesMatchIdIndexRoute = MatchesMatchIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesMatchIdRouteRoute,
} as any)
const TeamsTeamIdStatsRoute = TeamsTeamIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdSquadRoute = TeamsTeamIdSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const TeamsTeamIdMatchesRoute = TeamsTeamIdMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => TeamsTeamIdRouteRoute,
} as any)
const MatchesMatchIdStatsRoute = MatchesMatchIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => MatchesMatchIdRouteRoute,
} as any)
const MatchesMatchIdLineupsRoute = MatchesMatchIdLineupsRouteImport.update({
  id: '/lineups',
  path: '/lineups',
  getParentRoute: () => MatchesMatchIdRouteRoute,
} as any)
const MatchesMatchIdH2hRoute = MatchesMatchIdH2hRouteImport.update({
  id: '/h2h',
  path: '/h2h',
  getParentRoute: () => MatchesMatchIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$matchId': typeof MatchesMatchIdRouteRouteWithChildren
  '/teams/$teamId': typeof TeamsTeamIdRouteRouteWithChildren
  '/standings/': typeof StandingsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/$matchId/h2h': typeof MatchesMatchIdH2hRoute
  '/$matchId/lineups': typeof MatchesMatchIdLineupsRoute
  '/$matchId/stats': typeof MatchesMatchIdStatsRoute
  '/teams/$teamId/matches': typeof TeamsTeamIdMatchesRoute
  '/teams/$teamId/squad': typeof TeamsTeamIdSquadRoute
  '/teams/$teamId/stats': typeof TeamsTeamIdStatsRoute
  '/$matchId/': typeof MatchesMatchIdIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/standings': typeof StandingsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/$matchId/h2h': typeof MatchesMatchIdH2hRoute
  '/$matchId/lineups': typeof MatchesMatchIdLineupsRoute
  '/$matchId/stats': typeof MatchesMatchIdStatsRoute
  '/teams/$teamId/matches': typeof TeamsTeamIdMatchesRoute
  '/teams/$teamId/squad': typeof TeamsTeamIdSquadRoute
  '/teams/$teamId/stats': typeof TeamsTeamIdStatsRoute
  '/$matchId': typeof MatchesMatchIdIndexRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_matches/$matchId': typeof MatchesMatchIdRouteRouteWithChildren
  '/teams/$teamId': typeof TeamsTeamIdRouteRouteWithChildren
  '/standings/': typeof StandingsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/_matches/$matchId/h2h': typeof MatchesMatchIdH2hRoute
  '/_matches/$matchId/lineups': typeof MatchesMatchIdLineupsRoute
  '/_matches/$matchId/stats': typeof MatchesMatchIdStatsRoute
  '/teams/$teamId/matches': typeof TeamsTeamIdMatchesRoute
  '/teams/$teamId/squad': typeof TeamsTeamIdSquadRoute
  '/teams/$teamId/stats': typeof TeamsTeamIdStatsRoute
  '/_matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$matchId'
    | '/teams/$teamId'
    | '/standings/'
    | '/stats/'
    | '/teams/'
    | '/$matchId/h2h'
    | '/$matchId/lineups'
    | '/$matchId/stats'
    | '/teams/$teamId/matches'
    | '/teams/$teamId/squad'
    | '/teams/$teamId/stats'
    | '/$matchId/'
    | '/teams/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/standings'
    | '/stats'
    | '/teams'
    | '/$matchId/h2h'
    | '/$matchId/lineups'
    | '/$matchId/stats'
    | '/teams/$teamId/matches'
    | '/teams/$teamId/squad'
    | '/teams/$teamId/stats'
    | '/$matchId'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_matches/$matchId'
    | '/teams/$teamId'
    | '/standings/'
    | '/stats/'
    | '/teams/'
    | '/_matches/$matchId/h2h'
    | '/_matches/$matchId/lineups'
    | '/_matches/$matchId/stats'
    | '/teams/$teamId/matches'
    | '/teams/$teamId/squad'
    | '/teams/$teamId/stats'
    | '/_matches/$matchId/'
    | '/teams/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesMatchIdRouteRoute: typeof MatchesMatchIdRouteRouteWithChildren
  TeamsTeamIdRouteRoute: typeof TeamsTeamIdRouteRouteWithChildren
  StandingsIndexRoute: typeof StandingsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings/': {
      id: '/standings/'
      path: '/standings'
      fullPath: '/standings/'
      preLoaderRoute: typeof StandingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_matches/$matchId': {
      id: '/_matches/$matchId'
      path: '/$matchId'
      fullPath: '/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof TeamsTeamIdIndexRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/_matches/$matchId/': {
      id: '/_matches/$matchId/'
      path: '/'
      fullPath: '/$matchId/'
      preLoaderRoute: typeof MatchesMatchIdIndexRouteImport
      parentRoute: typeof MatchesMatchIdRouteRoute
    }
    '/teams/$teamId/stats': {
      id: '/teams/$teamId/stats'
      path: '/stats'
      fullPath: '/teams/$teamId/stats'
      preLoaderRoute: typeof TeamsTeamIdStatsRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/squad': {
      id: '/teams/$teamId/squad'
      path: '/squad'
      fullPath: '/teams/$teamId/squad'
      preLoaderRoute: typeof TeamsTeamIdSquadRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/teams/$teamId/matches': {
      id: '/teams/$teamId/matches'
      path: '/matches'
      fullPath: '/teams/$teamId/matches'
      preLoaderRoute: typeof TeamsTeamIdMatchesRouteImport
      parentRoute: typeof TeamsTeamIdRouteRoute
    }
    '/_matches/$matchId/stats': {
      id: '/_matches/$matchId/stats'
      path: '/stats'
      fullPath: '/$matchId/stats'
      preLoaderRoute: typeof MatchesMatchIdStatsRouteImport
      parentRoute: typeof MatchesMatchIdRouteRoute
    }
    '/_matches/$matchId/lineups': {
      id: '/_matches/$matchId/lineups'
      path: '/lineups'
      fullPath: '/$matchId/lineups'
      preLoaderRoute: typeof MatchesMatchIdLineupsRouteImport
      parentRoute: typeof MatchesMatchIdRouteRoute
    }
    '/_matches/$matchId/h2h': {
      id: '/_matches/$matchId/h2h'
      path: '/h2h'
      fullPath: '/$matchId/h2h'
      preLoaderRoute: typeof MatchesMatchIdH2hRouteImport
      parentRoute: typeof MatchesMatchIdRouteRoute
    }
  }
}

interface MatchesMatchIdRouteRouteChildren {
  MatchesMatchIdH2hRoute: typeof MatchesMatchIdH2hRoute
  MatchesMatchIdLineupsRoute: typeof MatchesMatchIdLineupsRoute
  MatchesMatchIdStatsRoute: typeof MatchesMatchIdStatsRoute
  MatchesMatchIdIndexRoute: typeof MatchesMatchIdIndexRoute
}

const MatchesMatchIdRouteRouteChildren: MatchesMatchIdRouteRouteChildren = {
  MatchesMatchIdH2hRoute: MatchesMatchIdH2hRoute,
  MatchesMatchIdLineupsRoute: MatchesMatchIdLineupsRoute,
  MatchesMatchIdStatsRoute: MatchesMatchIdStatsRoute,
  MatchesMatchIdIndexRoute: MatchesMatchIdIndexRoute,
}

const MatchesMatchIdRouteRouteWithChildren =
  MatchesMatchIdRouteRoute._addFileChildren(MatchesMatchIdRouteRouteChildren)

interface TeamsTeamIdRouteRouteChildren {
  TeamsTeamIdMatchesRoute: typeof TeamsTeamIdMatchesRoute
  TeamsTeamIdSquadRoute: typeof TeamsTeamIdSquadRoute
  TeamsTeamIdStatsRoute: typeof TeamsTeamIdStatsRoute
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
}

const TeamsTeamIdRouteRouteChildren: TeamsTeamIdRouteRouteChildren = {
  TeamsTeamIdMatchesRoute: TeamsTeamIdMatchesRoute,
  TeamsTeamIdSquadRoute: TeamsTeamIdSquadRoute,
  TeamsTeamIdStatsRoute: TeamsTeamIdStatsRoute,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
}

const TeamsTeamIdRouteRouteWithChildren =
  TeamsTeamIdRouteRoute._addFileChildren(TeamsTeamIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesMatchIdRouteRoute: MatchesMatchIdRouteRouteWithChildren,
  TeamsTeamIdRouteRoute: TeamsTeamIdRouteRouteWithChildren,
  StandingsIndexRoute: StandingsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
